### ISSUE TITLE
amalgamation libraries

### ISSUE THREAD

**Issue by graph** [dascandy/evoke#31]
**Is your feature request related to a problem? Please describe.**
amalgamation library

**Describe the solution you'd like**
cat source files together with minor preprocessing. See Sqlite.

**Describe alternatives you've considered**

**Additional context**
Some modules are simply amalgamations of sources together instead of a compiled library. This works in C++ very well when it comes to distributing modules. I understand modules is in the works for C++ but it's not here right now, and right now some projects use amalgamations of sources. Personally I like amalgamations more than the plans for modules that is comming to C++ and I don't think it will go away. A benefit of amalgamation also is that the amalgamated module can have C & C++ support.  What do you think of the direction for amalgamation support for evoke?

**Comment by dascandy** [comment]
From what I can tell amalgamation is a source transformation? In that case I'd expect the package manager to do this for you & distribute it - not the build system.

How would you see this fitting into a build system?

**Comment by graph** [comment]
Yes it's just a source transformation. It's a kind of library/module. Shared library, static library, amalgamated library. I see it being treated the same as a shared/static library. Instead of making a shared or static library with evoke, I would make a amalgamated library for distribution.  This is ofcourse only makes sense when the output of evoke is not an executable but just a library to be distributed.

**Comment by dascandy** [comment]
Right now Evoke only builds libraries that it's told to build; it does not deal with packaging, shipping or installing of packages. It may in the future be able to export a package definition (so that a package manager can then pick it up and package it) and in that case I think the "make this an amalgamated library" would also be on the package manager side.

I like the idea, but I think this is the wrong project to ask. Is it OK if I close this issue?
